baseURL: "https://ShubhamSupekar.github.io"
languageCode: en-us
title: Home
theme: PaperMod
disableThemeToggle: true  
params:
    profileMode:
        enabled: true
        title: "Hi! I'm Shubham." # optional default will be site title
        subtitle: "GOLANG, DOCKER, MongoDB, PostgreSQL,PRODUCTIVITY, BOOKS"  
        imageUrl: "https://avatars.githubusercontent.com/ShubhamSupekar" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: All Post
            url: /posts/
          - name: search
            url: /search/
    socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/shubham-supekar-42106916a/"
    - name: twitter
      url: "https://twitter.com/s_supekar_"
    - name: github
      url: "https://github.com/ShubhamSupekar"
    - name: email
      url: "shubham26supekar@gmail.com"

    cover: 
      linkFullImages: true
    
    ShowBreadCrumbs: true

    ShowShareButtons: true

    ShowPostNavLinks: true
    
    ShowReadingTime: true
    
    ShowToc: true

    TocOpen: true

    ShowCodeCopyButtons: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10